version: '2'
volumes:
    caddy_data:
    caddy_config:
    site:
services:    
    minio:
      image: minio/minio:RELEASE.2021-06-17T00-10-46Z
      volumes:
        - 'site:/data1'
      ports:
        - "9000:9000"
      environment:
        MINIO_ACCESS_KEY: myminio
        MINIO_SECRET_KEY: myminio123
        MINIO_REGION_NAME: myregion
      command: minio server /data1
      
    caddy:
      image: caddy:2.4.6
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - site:/usr/share
        - caddy_data:/data
        - caddy_config:/config
