FROM balenalib/%%BALENA_MACHINE_NAME%%

WORKDIR /usr/src/app

RUN \
    apt-get update && apt-get install -y wget && \
    wget https://dl.min.io/client/mc/release/linux-amd64/mc && \
    chmod +x mc
    

CMD [ "sleep", "infinity" ]
